farhaproject1/Pages/AdminUnit/AddNewBooking.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using farhaproject1.Data;
using farhaproject1.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace farhaproject1.Pages.AdminUnit
{
    public class AddNewBookingModel : PageModel
    {
        private readonly ApplicationDbContext _db;
        public AddNewBookingModel(ApplicationDbContext db)
        {
            _db = db;
        }
        [BindProperty]
        public string userid { get; set; }
        [BindProperty]
        public CustomerBooking customer { get; set; }
        public IList<HallInformation> Hall { get; set; }

        public IList<Decoration> Decoration { get; set; }
        public IList<DanceTeam> DanceTeam { get; set; }
        [BindProperty]
        public DateTime AddDate { get; set; }
        public async Task<IActionResult> OnGet(string AdminId = null)
        {
            if (AdminId == null)
            {
                var ClaimId = (ClaimsIdentity)User.Identity;//يجيب كل id
                var Claim = ClaimId.FindFirst(ClaimTypes.NameIdentifier);//idيجيب الي سوه لوك ان
                AdminId = Claim.Value;

            };

            userid = AdminId;
            Hall = await _db.HallInformation.Where(c => c.AdminId == userid).ToListAsync();
            Decoration = await _db.Decoration.Where(c => c.AdminId == userid).ToListAsync();
            DanceTeam = await _db.DanceTeam.Where(c => c.AdminId == userid).ToListAsync();

            return Page();
        }
        public async Task<IActionResult> OnPost()
        {
          
            customer.CustomerDate = AddDate;
            customer.AdminId = userid;
            _db.CustomerBooking.Add(customer);
            var AddDates = new ReservedDate
            {
                NewDate = AddDate,
                HallId =customer.HallId
            };
            _db.ReservedDate.Add(AddDates);
            await _db.SaveChangesAsync();
            return RedirectToPage("Booking",new { AdminId = userid });
        }
    }
}

farhaproject1/Pages/AdminUnit/AddNewDanceTeam.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using farhaproject1.Data;
using farhaproject1.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace farhaproject1.Pages.AdminUnit
{
    public class AddNewDanceTeamModel : PageModel
    {
        private readonly ApplicationDbContext _db;
        public AddNewDanceTeamModel(ApplicationDbContext db)
        {
            _db = db;

        }
        [BindProperty]
        public DanceTeam DanceTeam { get; set; }

        [BindProperty]
        public HallInformation HallInformation { get; set; }


        [BindProperty]
        public string userid { get; set; }
        public IActionResult OnGet(string AdminId = null)
        {
            if (AdminId == null)
            {
                var ClaimId = (ClaimsIdentity)User.Identity;//يجيب كل id
                var Claim = ClaimId.FindFirst(ClaimTypes.NameIdentifier);//idيجيب الي سوه لوك ان
                AdminId = Claim.Value;

            };

            userid = AdminId;
            return Page();

        }
        public async Task<IActionResult> OnPost()
        {
            var Information = new DanceTeam
            {
                AdminId = userid,
                Name = DanceTeam.Name,
                Price = DanceTeam.Price,


            };
            _db.DanceTeam.Add(Information);
            await _db.SaveChangesAsync();
            return RedirectToPage("Index");

        }

    }
}

farhaproject1/Pages/AdminUnit/AddNewDecoration.cshtml.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using farhaproject1.Data;
using farhaproject1.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace farhaproject1.Pages.AdminUnit
{
    public class AddNewDecorationModel : PageModel
    {
        private readonly ApplicationDbContext _db;
        private readonly IHostingEnvironment _host;

        public AddNewDecorationModel(ApplicationDbContext db, IHostingEnvironment host)
        {
            _db = db;
            _host = host;
        }
        [BindProperty]
        public IFormFile img { get; set; }
        [BindProperty]
        public Decoration Decoration { get; set; }
        [BindProperty]
        public string userid { get; set; }
        public IFormFile imgf { get; set; }

        public IList<AddPhoto> AddPhoto { get; set; }
        public IActionResult OnGet(string AdminId = null)
        {
            if (AdminId == null)
            {
                var ClaimId = (ClaimsIdentity)User.Identity;//يجيب كل id
                var Claim = ClaimId.FindFirst(ClaimTypes.NameIdentifier);//idيجيب الي سوه لوك ان
                AdminId = Claim.Value;

            };

            userid = AdminId;
            return Page();

        }
        public async Task<IActionResult> OnPostAddNewPhoto()
        {
            string newfileName = string.Empty;
            if (imgf != null && imgf.Length > 0)
            {

                string fn = imgf.FileName;
                if (IsImagValidate(fn))
                {
                    string extension = Path.GetExtension(fn);
                    newfileName = Guid.NewGuid().ToString() + extension;
                    string filename = Path.Combine(_host.WebRootPath + "/Img/", newfileName);
                    await imgf.CopyToAsync(new FileStream(filename, FileMode.Create));
                }
                else
                {
                    return Page();
                }
            }
            AddPhoto v = new AddPhoto
            {
                ImgFile = newfileName
            };
            _db.AddPhoto.Add(v);
            await _db.SaveChangesAsync();
            return Page();
        }
        public async Task<IActionResult> OnPostCreate()
        {

            string newfileName = string.Empty;
            if (img != null && img.Length > 0)
            {

                string fn = img.FileName;
                if (IsImagValidate(fn))
                {
                    string extension = Path.GetExtension(fn);
                    newfileName = Guid.NewGuid().ToString() + extension;
                    string filename = Path.Combine(_host.WebRootPath + "/Img/", newfileName);
                    await img.CopyToAsync(new FileStream(filename, FileMode.Create));
                }
                else
                {
                    return Page();
                }
            }
            var Information = new Decoration
            {
                AdminId = userid,
                Name=Decoration.Name,
                Price=Decoration.Price,
                Description = Decoration.Description,
                ImgFile=newfileName

                

            };
            _db.Decoration.Add(Information);
            await _db.SaveChangesAsync();
            AddPhoto = await _db.AddPhoto.ToListAsync();

            foreach (var item in AddPhoto)
            {
                var AddDate = new PhotoOfDecoration
                {
                    ImgFile = item.ImgFile,
                  DecorationId = Information.Id
                };
                _db.PhotoOfDecoration.Add(AddDate);

            }
            _db.AddPhoto.RemoveRange(AddPhoto);
            await _db.SaveChangesAsync();
            return RedirectToPage("Index");
        
    }
        private bool IsImagValidate(string filename)
        {
            string extension = Path.GetExtension(filename);
            if (extension.Contains(".png"))
                return true;
            if (extension.Contains(".PNG"))
                return true;
            if (extension.Contains(".jpeg"))
                return true;
            if (extension.Contains(".jpg"))
                return true;
            if (extension.Contains(".gif"))
                return true;
            return false;
        }
    }
}

farhaproject1/Pages/AdminUnit/Booking.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using farhaproject1.Data;
using farhaproject1.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace farhaproject1.Pages.AdminUnit
{
    public class BookingModel : PageModel
    {
        private readonly ApplicationDbContext _db;
        public BookingModel(ApplicationDbContext db)
        {
            _db = db;
        }
        [BindProperty]
        public string userid { get; set; }
        [BindProperty]
        public IList<CustomerBooking> customer { get; set; }
        public async Task<IActionResult> OnGet(string AdminId = null)
        {
            if (AdminId == null)
            {
                var ClaimId = (ClaimsIdentity)User.Identity;//يجيب كل id
                var Claim = ClaimId.FindFirst(ClaimTypes.NameIdentifier);//idيجيب الي سوه لوك ان
                AdminId = Claim.Value;

            };

            userid = AdminId;
           customer = await _db.CustomerBooking
                .Include(c=>c.HallInformation)
                .Include(c => c.Decoration)
                .Include(c=>c.DanceTeam)
               . Where(c => c.AdminId == userid).ToListAsync();
           

            return Page();
        }
       
    }
}

farhaproject1/Pages/AdminUnit/DeleteBooking.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using farhaproject1.Data;
using farhaproject1.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace farhaproject1.Pages.AdminUnit
{
    public class DeleteBookingModel : PageModel
    {
        private readonly ApplicationDbContext _db;
        public DeleteBookingModel(ApplicationDbContext db)
        {
            _db = db;
        }
      
        [BindProperty]
        public CustomerBooking customer { get; set; }
    
        public ReservedDate ReservedDate { get; set; }
        public async Task<IActionResult> OnGet(int Id)
        {

            customer = await _db.CustomerBooking.FirstOrDefaultAsync(customer => customer.Id == Id);
            return Page();
        }
        public async Task<IActionResult> OnPost()
        {
            ReservedDate reserveddate = _db.ReservedDate.FirstOrDefault(c => c.HallId == customer.HallId && c.NewDate == customer.CustomerDate);
            _db.ReservedDate.Remove(reserveddate);
            _db.CustomerBooking.Remove(customer);
           
        await _db.SaveChangesAsync();
            return RedirectToPage("Booking", new { AdminId = customer.AdminId });
        }
    }
}

farhaproject1/Pages/AdminUnit/EditHall.cshtml.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using farhaproject1.Data;
using farhaproject1.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace farhaproject1.Pages.AdminUnit
{
    public class EditHallModel : PageModel
    {
        private readonly ApplicationDbContext _db;
        private readonly IHostingEnvironment _host;


        public EditHallModel(ApplicationDbContext db, IHostingEnvironment host)
        {
            _db = db;
            _host = host;
        }
        [BindProperty]
        public IFormFile img { get; set; }

        [BindProperty]
        public HallInformation HallInformation { get; set; }
        [BindProperty]
        public IList<ReservedDate> ReservedDate { get; set; }
        public async Task<IActionResult> OnGet(int Id)
        {
            if (Id == null)
            {

                return NotFound();
            }
            HallInformation = await _db.HallInformation.FirstOrDefaultAsync(m => m.Id == Id);
            if (HallInformation == null)
            {
                return NotFound();
            }
            ReservedDate = await _db.ReservedDate.Where(c => c.HallId == Id).ToListAsync();
            return Page();
        }
        public async Task<IActionResult> OnPostDeleteHall(int Id)
        {
            var DateOfHallFromDb = await _db.ReservedDate.FirstOrDefaultAsync(m => m.Id == Id);

            _db.ReservedDate.Remove(DateOfHallFromDb);

            await _db.SaveChangesAsync();

            return RedirectToPage("EditHall",new { Id = DateOfHallFromDb.HallId });

        }
      
        public async Task<IActionResult> OnPostUpdate()
        {
            string newfileName = string.Empty;
            if (img != null && img.Length > 0)
            {

                string fn = img.FileName;
                if (IsImagValidate(fn))
                {
                    string extension = Path.GetExtension(fn);
                    newfileName = Guid.NewGuid().ToString() + extension;
                    string filename = Path.Combine(_host.WebRootPath + "/Img/", newfileName);
                    await img.CopyToAsync(new FileStream(filename, FileMode.Create));
                }
                else
                {
                    return Page();
                }
            }
            var InformationOfHallFromDb = await _db.HallInformation.FirstOrDefaultAsync(m => m.Id == HallInformation.Id);

            if (InformationOfHallFromDb == null)
            {
                return NotFound();
            }
            InformationOfHallFromDb.AdminId = HallInformation.AdminId;
            InformationOfHallFromDb.HallName= HallInformation.HallName;
            InformationOfHallFromDb.Price = HallInformation.Price;
            InformationOfHallFromDb.Size = HallInformation.Size;
            InformationOfHallFromDb.Description = HallInformation.Description;
            InformationOfHallFromDb.ImgFile = newfileName;
            await _db.SaveChangesAsync();

            return RedirectToPage("Index");

        }
        private bool IsImagValidate(string filename)
        {
            string extension = Path.GetExtension(filename);
            if (extension.Contains(".png"))
                return true;
            if (extension.Contains(".PNG"))
                return true;
            if (extension.Contains(".jpeg"))
                return true;
            if (extension.Contains(".jpg"))
                return true;
            if (extension.Contains(".gif"))
                return true;
            return false;
        }
    }
}

farhaproject1/Pages/AdminUnit/Reservation.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using farhaproject1.Data;
using farhaproject1.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace farhaproject1.Pages.AdminUnit
{
    public class ReservationModel : PageModel
    {
        private readonly ApplicationDbContext _db;
        public ReservationModel(ApplicationDbContext db)
        {
            _db=db;
        }
        [BindProperty]
        public IList<TReservation> TReservation { get; set; }
        [BindProperty]
        public int IdR { get; set; }
        public CustomerBooking CustomerBooking { get; set; }
        public async Task<IActionResult> OnGet(String Id)
        {
            if (Id == null)
            {
                var ClaimId = (ClaimsIdentity)User.Identity;//يجيب كل id
                var Claim = ClaimId.FindFirst(ClaimTypes.NameIdentifier);//idيجيب الي سوه لوك ان
               Id = Claim.Value;

            };
            TReservation = await _db.TReservation.Include(c=>c.HallInformation).Include(c=>c.DanceTeam).Include(c=>c.Decoration).Where(c => c.AdminId == Id).ToListAsync();
                return Page();
        }
        public async Task<IActionResult> OnPostDeny()
        {
            var a = await _db.TReservation.FirstOrDefaultAsync(c => c.Id == IdR);
            _db.TReservation.Remove(a);
            await _db.SaveChangesAsync();
            return Page();
        }
        public async Task<IActionResult> OnPostAccept()
        {
            var a = await _db.TReservation.FirstOrDefaultAsync(c => c.Id == IdR);
            CustomerBooking b = new CustomerBooking
            {
                HallId = a.HallId,
                DecorationId=a.DecorationId,
                DanceTeamId=a.DanceTeamId,
                AdminId=a.AdminId,
                CustomerDate=a.D,
                Name=a.Name,
                PhoneNumber=a.PhoneNumber
                
            };
            _db.CustomerBooking.Add(b);
            _db.TReservation.Remove(a);
            var AddDates = new ReservedDate
            {
                NewDate =a.D,
                HallId = a.HallId
            };
            _db.ReservedDate.Add(AddDates);
            await _db.SaveChangesAsync();



            return Page();
        }
    }
}

farhaproject1/Pages/AdminUnit/AddNewDanceTeam.cshtml
@page
@model farhaproject1.Pages.AdminUnit.AddNewDanceTeamModel
@{
    ViewData["Title"] = "AddNewDanceTeam";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<head>
    <link rel="stylesheet" href="~/css/style.css" />

</head>


<section class="ftco-section bg-secondary" id="rsvp-section">

    <div class="container">
        <div class="row justify-content-center pb-5 pt-2">
            <div class="col-md-12 text-center heading-section">

                <h2 class="mb-3" style="color:#f58499;">Add New Dance Team </h2>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-md-7">

                <form method="post" enctype="multipart/form-data" class="rsvp-form ">
                    <input type="hidden" asp-for="userid" />
                    <input type="hidden" asp-for="DanceTeam.Id" />
                    <input type="hidden" asp-for="DanceTeam.AdminId" />
                    <div class="">
                        <div class="form-group">
                            <input type="text" asp-for="DanceTeam.Name" class="form-control" placeholder="Name">
                            <p asp-validation-for="DanceTeam.Name" class="text-danger"> </p>
                        </div>
                        <div class="form-group">
                            <input type="text" asp-for="DanceTeam.Price" class="form-control" placeholder="Price">
                            <p asp-validation-for="DanceTeam.Price" class="text-danger"> </p>
                        </div>




                        <div class="form-group float-right">
                            <input type="submit" asp-page-handler="Create" class="btn btn-info py-3 px-5 mr-1" value="Create" />
                        </div>

                        <div class="form-group ">
                            <a asp-page="Index" class="btn btn-primary py-3 px-5 mr-5" value="Back"> Back </a>
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>

</section>

farhaproject1/Pages/AdminUnit/AddNewDecoration.cshtml
@page
@model farhaproject1.Pages.AdminUnit.AddNewDecorationModel
@{
    ViewData["Title"] = "AddNewDecoration";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<head>
    <link rel="stylesheet" href="~/css/style.css" />

</head>


<section class="ftco-section bg-secondary pt-2" id="rsvp-section">

    <div class="container">
        <div class="row justify-content-center pb-5">
            <div class="col-md-12 text-center heading-section">

                <h2 class="mb-3" style="color:#f58499;">Add New Decoration</h2>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-md-7">

                <form method="post" enctype="multipart/form-data" class="rsvp-form ">
                    <input type="hidden" asp-for="userid" />
                    <input type="hidden" asp-for="Decoration.Id" />
                    <input type="hidden" asp-for="Decoration.AdminId" />
                    <div class="">
                        <div class="form-group">
                            <input type="text" asp-for="Decoration.Name" class="form-control" placeholder="Name">
                            <p asp-validation-for="Decoration.Name" class="text-danger"> </p>
                        </div>
                        <div class="form-group">
                            <input type="text" asp-for="Decoration.Description" class="form-control" placeholder="Description">
                            <p asp-validation-for="Decoration.Description" class="text-danger"> </p>
                        </div>
                        <div class="form-group">
                            <input type="text" asp-for="Decoration.Price" class="form-control" placeholder="Price">
                            <p asp-validation-for="Decoration.Price" class="text-danger"> </p>
                        </div>
                        <div class="form-group">

                            <input type="file" asp-for="img" class="form-control" />


                            <p>Add Multiple photo</p>

                            <input type="file" asp-for="imgf" class="form-control" />


                            <button type="submit" asp-page-handler="AddNewPhoto" class="btn btn-success form-control" style="width:60px;">
                                Add
                            </button>
                        </div>



                        <div class="form-group float-right">
                            <input type="submit" asp-page-handler="Create" class="btn btn-info py-3 px-5 mr-1" value="Create" />
                        </div>

                        <div class="form-group ">
                            <a asp-page="Index" class="btn btn-primary py-3 px-5 mr-5" value="Back"> Back </a>
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>

</section>

farhaproject1/Pages/AdminUnit/AddNewHall.cshtml
@page
@model farhaproject1.Pages.AdminUnit.AddNewHallModel
@{
    ViewData["Title"] = "AddNewHall";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<head>
    <link rel="stylesheet" href="~/css/style.css" />

</head>


<section class="ftco-section bg-secondary pt-2" id="rsvp-section">

    <div class="container ">
        <div class="row justify-content-center pb-5 ">
            <div class="col-md-12 text-center heading-section">

                <h2 class="mb-3" style="color:#f58499;">Add New Hall</h2>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-md-8">

                <form method="post" enctype="multipart/form-data" class="rsvp-form ">

                    <input type="hidden" asp-for="userid" />
                    <input type="hidden" asp-for="HallInformation.Id" />
                    <div class="">
                        <div class="form-group">
                            <input type="text" asp-for="HallInformation.HallName" class="form-control" placeholder="Name">
                            <p asp-validation-for="HallInformation.HallName" class="text-danger"> </p>
                        </div>
                        <div class="form-group">
                            <input type="text" asp-for="HallInformation.Description" class="form-control" placeholder="Description">
                            <p asp-validation-for="HallInformation.Description" class="text-danger"> </p>
                        </div>
                        <div class="form-group">
                            <input type="text" asp-for="HallInformation.Size" class="form-control" placeholder="Size">
                            <p asp-validation-for="HallInformation.Size" class="text-danger"> </p>
                        </div>
                        <div class="form-group">
                            <input type="text" asp-for="HallInformation.Price" class="form-control" placeholder="Price">
                            <p asp-validation-for="HallInformation.Price" class="text-danger"> </p>
                        </div>

                        <div class="form-group">

                            <input type="file" asp-for="img" class="form-control" />


                            <p>Add Multiple photo</p>

                            <input type="file" asp-for="imgf" class="form-control" />


                            <button type="submit" asp-page-handler="AddNewPhoto" class="btn btn-success form-control mt-3" style="width:60px;">
                                Add
                            </button>
                        </div>

                        <div class="form-group float-right">
                            <input type="submit" asp-page-handler="Create" class="btn btn-info py-3 px-5 mr-1" value="Create" />
                        </div>

                        <div class="form-group ">
                            <a asp-page="Index" class="btn btn-primary py-3 px-5 mr-5" value="Back"> Back </a>
                        </div>



                    </div>
                </form>
            </div>
        </div>
    </div>

</section>

farhaproject1/Pages/AdminUnit/EditDanceTeam.cshtml
@page
@model farhaproject1.Pages.AdminUnit.EditDanceTeamModel
@{
    ViewData["Title"] = "EditDanceTeam";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<head>
    <link rel="stylesheet" href="~/css/style.css" />

</head>


<section class="ftco-section bg-secondary" id="rsvp-section">

    <div class="container">
        <div class="row justify-content-center pb-5">
            <div class="col-md-12 text-center heading-section">

                <h2 class="mb-3" style="color:#f58499;">Edit Dance Team ??</h2>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-md-7">
                <form method="post" class="rsvp-form ">
                    <input type="hidden" asp-for="DanceTeam.Id" />
                    <input type="hidden" asp-for="DanceTeam.AdminId" />
                    <div class="">
                        <div class="form-group">
                            <input type="text" asp-for="DanceTeam.Name" class="form-control" placeholder="Name" />
                            <p asp-validation-for="DanceTeam.Name" class="text-danger"> </p>
                        </div>
                        <div class="form-group">
                            <input type="number" asp-for="DanceTeam.Price" class="form-control" placeholder="Price" />
                            <p asp-validation-for="DanceTeam.Price" class="text-danger"> </p>
                        </div>


                        <div class="form-group float-right">
                            <input type="submit" class="btn btn-info py-3 px-5 mr-1 " value="Update" />
                        </div>

                        <div class="form-group ">
                            <a asp-page="Index" class="btn btn-primary py-3 px-5 mr-5" value="Back"> Back </a>
                        </div>

                    </div>




                </form>
            </div>
        </div>
    </div>

</section>

farhaproject1/Pages/AdminUnit/Reservation.cshtml
@page
@model farhaproject1.Pages.AdminUnit.ReservationModel
@{
    ViewData["Title"] = "Reservation";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}


<head>
    <link rel="stylesheet" href="~/css/style.css" />

</head>


@if (Model.TReservation.Count() != 0)
{
    <section class="ftco-section bg-secondary pt-1" id="rsvp-section">


        @foreach (var item in Model.TReservation)
        {
            <div class="container">
                <div class="row justify-content-center pb-3">
                    <div class="col-md-12 text-center heading-section">

                        <h2 class="mb-3" style="color:#f58499;">Request</h2>
                    </div>
                </div>
                <div class="row justify-content-center">
                    <div class="col-md-7">

                        <form method="post" enctype="multipart/form-data" class="rsvp-form ">


                            <div class="">
                                <div class="form-group">

                                    <li class="list-group-item text-dark"> @Html.DisplayNameFor(m => item.Name) : @Html.DisplayFor(m => item.Name) </li>
                                </div>
                                <div class="form-group">

                                    <li class="list-group-item text-dark"> @Html.DisplayNameFor(m => item.PhoneNumber) : @Html.DisplayFor(m => item.PhoneNumber) </li>
                                </div>
                            </div>
                            <div class="">
                                <div class="form-group">
                                    <input type="date" asp-for="@item.D" placeholder="Pick the date" class="form-control datepicker datepicker-inline">
                                </div>
                                <div class="form-group">
                                    <li class="list-group-item text-dark">@Html.DisplayNameFor(m => item.TotalPrice) : @Html.DisplayFor(m => item.TotalPrice) IQD </li>
                                    @*<input type="hidden" asp-for="TotalPrices" />*@
                                </div>
                            </div>

                            <div class="">
                                <div class="form-group">
                                    <li class="list-group-item text-dark">@Html.DisplayNameFor(m => item.HallInformation.HallName) :@Html.DisplayFor(m => item.HallInformation.HallName) </li>


                                </div>

                            </div>

                            <div class="">
                                <div class="form-group">

                                    <li class="list-group-item text-dark"> @Html.DisplayNameFor(m => item.Decoration.Name) : @Html.DisplayFor(m => item.Decoration.Name) </li>
                                </div>
                                <div class="form-group">

                                    <li class="list-group-item text-dark"> @Html.DisplayNameFor(m => item.DanceTeam.Name) : @Html.DisplayFor(m => item.DanceTeam.Name) </li>

                                </div>
                                <input type="hidden" asp-for="@Model.IdR" value="@item.Id" />

                                <div class="form-group float-right">


                                    <input type="submit" value="Accept" asp-page-handler="Accept" class="btn btn-primary py-3 px-5 mr-1 ">

                                </div>
                                <div class="form-group ">
                                    <input type="submit" value="Deny" asp-page-handler="Deny" class="btn btn-primary py-3 px-5 mr-1 ">


                                </div>

                            </div>
                        </form>


                    </div>
                </div>
            </div>
        }
    </section>}
else
{
    <h2 class="mb-3" style="color:#f58499;">No Request</h2>
}